# Generated by Django 5.2.8 on 2025-11-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renta',
            name='days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='renta',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
